name: Synchronize Todoist
on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    

jobs:
  sync_issues:
    name: Synchronize // ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Issues
            query: archived:false sort:updated-desc assignee:cobraz updated:>2021-01-01 -label:backlog
            file-name: generic.json
          - name: Pull Requests
            query: is:pr archived:false sort:updated-desc review-requested:cobraz -label:backlog
            file-name: pr.json
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: octokit
          repo: request-action

      - run: gh gist view ${{ secret.GIST_ID }} -f ${{ matrix.file-name }} > ./sync.json

      - name: Sync issues
        uses: ./
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: ${{ matrix.query }}
          sync-file-name: ./sync.json
      
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: ${{ secret.GIST_ID }}
          gist_file_name: ${{ matrix.file-name }}
          file_path: ./sync.json
